Algoritmo "exercicioNotas"

Var

 nota1, nota2, notaFinal : real

Inicio

   escreva("Digite a primeira nota: ")
   leia(nota1)
   escreva("Digite a segunda nota: ")
   leia(nota2)
   
   notaFinal <- nota1 + nota2;
   
   se notafinal >= 60 entao
      escreval("NOTA FINAL = ",notaFinal)
   senao
      escreval("NOTA FINAL = ",notaFinal)
      escreval("REPROVADO")
   fimse


Fimalgoritmo